POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 1,
  "name" : "남길동",
  "id" : "user1",
  "password" : "1234",
  "email" : "user1@nhn.com",
  "residentRegistrationNumber" : "130914-1234561",
  "genderCode" : "남",
  "birthDate" : "1913-09-14T07:22:00",
  "birthPlaceCode" : "자택",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}

###

PUT /residents/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "deathDate" : "2019-12-31T23:59:59",
  "deathPlaceCode" : "주택",
  "deathPlaceAddress" : "강원도 고성군 금강산로 290번길"
}

###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 2,
  "name" : "남석환",
  "id" : "user2",
  "password" : "1234",
  "email" : "user2@nhn.com",
  "residentRegistrationNumber" : "540514-1234562",
  "genderCode" : "남",
  "birthDate" : "1954-05-14T17:30:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}
###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 3,
  "name" : "박한나",
  "id" : "user3",
  "password" : "1234",
  "email" : "user3@nhn.com",
  "residentRegistrationNumber" : "540514-1234562",
  "genderCode" : "여",
  "birthDate" : "1955-10-22T11:15:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "540514-1234562"
}
###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 4,
  "name" : "남기준",
  "id" : "user4",
  "password" : "1234",
  "email" : "user4@nhn.com",
  "residentRegistrationNumber" : "790510-1234564",
  "genderCode" : "남",
  "birthDate" : "1979-05-10T20:45:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}
###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 5,
  "name" : "이주은",
  "id" : "user5",
  "password" : "1234",
  "email" : "user5@nhn.com",
  "residentRegistrationNumber" : "820821-1234565",
  "genderCode" : "여",
  "birthDate" : "1982-08-21T01:28:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 수원시 팔달구 효원로 1번길"
}
###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 6,
  "name" : "이선미",
  "id" : "user6",
  "password" : "1234",
  "email" : "user6@nhn.com",
  "residentRegistrationNumber" : "851205-1234566",
  "genderCode" : "여",
  "birthDate" : "1985-12-05T22:01:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 수원시 팔달구 효원로 1번길"
}
###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 7,
  "name" : "남기석",
  "id" : "user7",
  "password" : "1234",
  "email" : "user7@nhn.com",
  "residentRegistrationNumber" : "120315-1234567",
  "genderCode" : "남",
  "birthDate" : "2012-03-15T14:59:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
}
